load("@rules_java//java:defs.bzl", "java_binary", "java_library")
load("//legend-pure/legend-pure-core/legend-pure-m3-core:pure.bzl", "pure_compiled_metadata_gen")
load("//tools/build_rules:legend_java_library.bzl", "legend_java_library")

java_library(
    name = "boot",
    srcs = [
        "src/main/java/org/finos/legend/engine/external/language/java/runtime/compiler/CoreJavaRuntimeCompilerCodeRepositoryProvider.java",
    ],
    resource_strip_prefix = "legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-javaCompiler/legend-engine-pure-functions-javaCompiler-pure/src/main/resources",
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "//legend-engine/legend-engine-xts-java/legend-engine-xt-javaGeneration-pure",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)

java_binary(
    name = "compiled_metadata_generator",
    main_class = "org.finos.legend.pure.runtime.java.compiled.generation.orchestrator.JavaCodeGeneration",
    visibility = ["//visibility:public"],
    runtime_deps = [
        ":boot",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-javaCompiler/legend-engine-pure-runtime-java-extension-compiled-functions-javaCompiler",
        "//legend-engine/legend-engine-xts-java/legend-engine-xt-javaGeneration-pure",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-diagram/legend-pure-m2-dsl-diagram-grammar",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-graph/legend-pure-m2-dsl-graph-grammar",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-grammar",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-path/legend-pure-m2-dsl-path-grammar",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-store/legend-pure-m2-dsl-store-grammar",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-grammar",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "//legend-pure/legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-grammar",
    ],
)

legend_java_library(
    name = "legend-engine-pure-functions-javaCompiler-pure",
    srcs = [],
    pure_generator = ":compiled_metadata_generator",
    pure_repository = "core_external_language_java_compiler",
    visibility = ["//visibility:public"],
    deps = [
        ":boot",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-javaCompiler/legend-engine-pure-runtime-java-extension-shared-functions-javaCompiler",
        "//legend-engine/legend-engine-xts-java/legend-engine-xt-javaGeneration-pure",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled:compiled_engine_boot",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled:core_gen",
        "@legend_maven//:com_googlecode_json_simple_json_simple",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)

pure_compiled_metadata_gen(
    name = "core_external_language_java_compiler_compiled_graph",
    srcs = glob(["src/main/resources/**/*"]),
    out = "core_external_language_java_compiler_compiled_metadata.jar",
    module_name = "core_external_language_java_compiler",
    tool = ":compiled_metadata_generator",
    visibility = ["//visibility:public"],
)

java_import(
    name = "core_external_language_java_compiler_compiled_graph_import",
    jars = [":core_external_language_java_compiler_compiled_metadata.jar"],
    visibility = ["//visibility:public"],
)
