load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "legend-engine-xt-relationalStore-protocol",
    srcs = [
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/RelationalProtocolExtension.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/RelationResultType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/RelationType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/CreateAndPopulateTempTableExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/RelationalBlockExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/RelationalClassInstantiationExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/RelationalDataTypeInstantiationExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/RelationalExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/RelationalInstantiationExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/RelationalRelationDataInstantiationExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/RelationalSaveNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/RelationalTdsInstantiationExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/SQLExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/TempTableColumnMetaData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/LoadFromResultSetAsValueTuplesTempTableStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/LoadFromSubQueryTempTableStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/LoadFromTempFileTempTableStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/RelationalClassQueryTempTableGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/RelationalCrossRootGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/RelationalCrossRootQueryTempTableGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/RelationalGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/RelationalPrimitiveQueryGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/RelationalRootGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/RelationalRootQueryTempTableGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/RelationalTempTableGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/TempTableStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/DatabaseConnection.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/DatabaseType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/GenerationFeaturesConfig.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/RelationalDatabaseConnection.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/RelationalQueryGenerationConfig.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/ApiTokenAuthenticationStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/AuthenticationStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/AuthenticationStrategyVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/DefaultH2AuthenticationStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/DelegatedKerberosAuthenticationStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/GCPApplicationDefaultCredentialsAuthenticationStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/GCPWorkloadIdentityFederationAuthenticationStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/MiddleTierUserNamePasswordAuthenticationStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/OAuthAuthenticationStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/TestDatabaseAuthenticationStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/authentication/UserNamePasswordAuthenticationStrategy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/flows/DatabaseAuthenticationFlowKey.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/legacy/PostProcessorParameter.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/legacy/PostProcessorWithParameter.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/postprocessor/ExtractSubQueriesAsCTEsPostProcessor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/postprocessor/Mapper.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/postprocessor/MapperPostProcessor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/postprocessor/PostProcessor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/postprocessor/RelationalMapperPostProcessor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/postprocessor/SchemaNameMapper.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/postprocessor/TableNameMapper.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/DatasourceSpecification.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/DatasourceSpecificationVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/EmbeddedH2DatasourceSpecification.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/LocalH2DatasourceSpecification.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/connection/specification/StaticDatasourceSpecification.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/data/RelationalCSVData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/data/RelationalCSVTable.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/mapping/EmbeddedRelationalPropertyMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/mapping/FilterMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/mapping/FilterPointer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/mapping/InlineEmbeddedPropertyMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/mapping/OtherwiseEmbeddedRelationalPropertyMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/mapping/RelationalAssociationMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/mapping/RelationalClassMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/mapping/RelationalPropertyMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/mapping/RootRelationalClassMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/mapping/TablePtr.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/mapping/mappingTest/RelationalInputData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/mapping/mappingTest/RelationalInputType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/Column.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/ColumnMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/Database.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/Filter.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/Join.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/MultiGrainFilter.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/Schema.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/Table.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/TabularFunction.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/View.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/BigInt.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Binary.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Bit.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Char.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/DataType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Date.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Decimal.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Double.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Float.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Integer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Json.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Numeric.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Other.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Real.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/SemiStructured.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/SmallInt.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Timestamp.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/TinyInt.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/VarChar.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/datatype/Varbinary.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/milestoning/BusinessMilestoning.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/milestoning/BusinessSnapshotMilestoning.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/milestoning/Milestoning.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/milestoning/ProcessingMilestoning.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/milestoning/ProcessingSnapshotMilestoning.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/operation/DynaFunc.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/operation/ElementWithJoins.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/operation/JoinPointer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/operation/Literal.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/operation/LiteralList.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/operation/RelationalOperationElement.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/operation/TableAliasColumn.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/relational/model/result/SQLResultColumn.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/DatabaseInstance.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/executionContext/RelationalExecutionContext.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/executionContext/TableForeignColumns.java",
    ],
    resource_strip_prefix = "legend-engine/legend-engine-xts-relationalStore/legend-engine-xt-relationalStore-generation/legend-engine-xt-relationalStore-protocol/src/main/resources",
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure:protocol-pure-v1",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:org_mongodb_bson",
    ],
)
