load("@rules_java//java:defs.bzl", "java_binary", "java_library")

java_binary(
    name = "Generator",
    main_class = "org.finos.legend.pure.runtime.java.compiled.generation.orchestrator.JavaCodeGeneration",
    runtime_deps = [
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled:legend-pure-runtime-java-engine-compiled",
        "//legend-pure/legend-pure-core/legend-pure-m3-core:legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4:legend-pure-m4",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-path/legend-pure-m2-dsl-path-pure",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-path:pure_platform_dsl_path_par_lib",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-path/legend-pure-m2-dsl-path-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-platform-modular-generation/legend-engine-pure-platform-java",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
    visibility = ["//visibility:public"],
)

load("//tools/build_rules:pure_compiled.bzl", "pure_sources")

pure_sources(
    name = "platform_dsl_path_java_src",
    repository = "platform_dsl_path",
    generator = ":Generator",
    visibility = ["//visibility:public"],
)

java_library(
    name = "legend-engine-pure-platform-dsl-path-java",
    srcs = [":platform_dsl_path_java_src"],
    deps = [
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled:legend-pure-runtime-java-engine-compiled",
        "//legend-pure/legend-pure-core/legend-pure-m3-core:legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4:legend-pure-m4",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-path/legend-pure-m2-dsl-path-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-platform-modular-generation/legend-engine-pure-platform-java",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
    javacopts = ["-Xep:IdentityBinaryExpression:OFF", "-Xep:ComparableType:OFF", "-Xep:IsInstanceIncompatibleType:OFF"],
    visibility = ["//visibility:public"],
)
