load("@rules_java//java:defs.bzl", "java_binary", "java_library")

java_library(
    name = "resources",
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
)

java_library(
    name = "resources_generator",
    resources = glob(
        ["src/main/resources/**/*"],
        exclude = ["**/services/org.finos.legend.pure.runtime.java.compiled.extension.CompiledExtension"],
    ),
    visibility = ["//visibility:public"],
)

java_binary(
    name = "Generator",
    main_class = "org.finos.legend.pure.runtime.java.compiled.generation.orchestrator.JavaCodeGeneration",
    visibility = ["//visibility:public"],
    runtime_deps = [
        ":boot",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-compiled-functions-relation",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-shared-functions-relation",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-functions-standard-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-runtime-java-extension-shared-functions-standard",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-runtime-java-extension-compiled-functions-unclassified",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-variant/legend-engine-pure-runtime-java-extension-compiled-functions-variant",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-platform-modular-generation/legend-engine-pure-platform-java",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)

load("//tools/build_rules:legend_java_library.bzl", "legend_java_library")

java_library(
    name = "boot",
    srcs = [
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/Base_Compiled_Standard_PCTReportProvider.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/natives/date/operation/TimeBucketDateTime.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/natives/date/operation/TimeBucketStrictDate.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/natives/math/trigonometry/CosH.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/natives/math/trigonometry/SinH.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/natives/math/trigonometry/TanH.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/natives/string/generation/Guid.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/natives/tbd/BitAnd.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/natives/tbd/BitNot.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/natives/tbd/BitOr.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/natives/tbd/BitShiftLeft.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/natives/tbd/BitShiftRight.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/natives/tbd/BitXor.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/natives/tbd/HashCode.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/StandardFunctionsExtensionCompiled.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/standard/compiled/StandardFunctionsHelper.java",
    ],
    javacopts = ["-Xep:ComparableType:OFF"],
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-compiled-functions-relation",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-shared-functions-relation",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-runtime-java-extension-shared-functions-standard",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-runtime-java-extension-compiled-functions-unclassified",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-variant/legend-engine-pure-runtime-java-extension-compiled-functions-variant",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-platform-modular-generation/legend-engine-pure-platform-java",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)

legend_java_library(
    name = "legend-engine-pure-runtime-java-extension-compiled-functions-standard",
    src_root = "legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-runtime-java-extension-compiled-functions-standard/src/main/java",
    srcs = [],
    pure_repository = "core_functions_standard",
    pure_srcs = ["//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-functions-standard-pure"],
    pure_generator = ":Generator",
    include_metadata = True,
    javacopts = ["-Xep:ComparableType:OFF"],
    visibility = ["//visibility:public"],
    exports = [
        ":boot",
    ],
    deps = [
        ":boot",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-compiled-functions-relation",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-shared-functions-relation",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-functions-standard-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-runtime-java-extension-shared-functions-standard",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-runtime-java-extension-compiled-functions-unclassified",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-variant/legend-engine-pure-runtime-java-extension-compiled-functions-variant",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-platform-modular-generation/legend-engine-pure-platform-java",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-pure",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
