load("@rules_java//java:defs.bzl", "java_binary", "java_library")

java_binary(
    name = "Generator",
    main_class = "org.finos.legend.pure.runtime.java.compiled.generation.orchestrator.JavaCodeGeneration",
    runtime_deps = [
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled:legend-pure-runtime-java-engine-compiled",
        "//legend-pure/legend-pure-core/legend-pure-m3-core:legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4:legend-pure-m4",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
    visibility = ["//visibility:public"],
)

load("//tools/build_rules:pure_compiled.bzl", "pure_sources")

pure_sources(
    name = "platform_java_src",
    repository = "platform",
    generator = ":Generator",
    exclusions = [
        "org/finos/legend/pure/generated/CoreGen.java",
        "org/finos/legend/pure/generated/Root_meta_pure_functions_lang_KeyValue.java",
    ],
    visibility = ["//visibility:public"],
)

java_library(
    name = "legend-engine-pure-platform-java",
    srcs = [":platform_java_src"],
    deps = [
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled:legend-pure-runtime-java-engine-compiled",
        "//legend-pure/legend-pure-core/legend-pure-m3-core:legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4:legend-pure-m4",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
    javacopts = ["-Xep:IdentityBinaryExpression:OFF", "-Xep:ComparableType:OFF", "-Xep:IsInstanceIncompatibleType:OFF"],
    visibility = ["//visibility:public"],
)
