load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "legend-engine-pure-runtime-java-extension-shared-functions-variant",
    srcs = [
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/variant/VariantInstanceImpl.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
