load("@rules_java//java:defs.bzl", "java_binary", "java_library")
load("//tools/build_rules:legend_java_library.bzl", "legend_java_library")

java_library(
    name = "resources",
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
)

java_library(
    name = "resources_generator",
    resources = glob(
        ["src/main/resources/**/*"],
        exclude = ["**/services/org.finos.legend.pure.runtime.java.compiled.extension.CompiledExtension"],
    ),
    visibility = ["//visibility:public"],
)

java_binary(
    name = "Generator",
    main_class = "org.finos.legend.pure.runtime.java.compiled.generation.orchestrator.JavaCodeGeneration",
    visibility = ["//visibility:public"],
    runtime_deps = [
        ":boot",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-functions-unclassified-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-runtime-java-extension-shared-functions-unclassified",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "@legend_maven//:commons_codec_commons_codec",
        "@legend_maven//:io_opentracing_opentracing_api",
        "@legend_maven//:io_opentracing_opentracing_util",
        "@legend_maven//:org_apache_commons_commons_text",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)

java_library(
    name = "boot",
    srcs = [
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/Base_Compiled_PCTReportProvider.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/FunctionsExtensionCompiled.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/FunctionsHelper.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/MayExecuteAlloyTest.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/MayExecuteLegendTest.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/Profile.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/cipher/Decrypt.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/cipher/Encrypt.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/collection/Get.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/collection/Repeat.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/date/DayOfWeekNumber.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/date/DayOfYear.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/date/Now.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/date/Today.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/date/WeekOfYear.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/hash/Hash.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/io/ReadFile.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/io/http/Http.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/lang/MutateAdd.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/meta/CompileValueSpecification.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/meta/FunctionDescriptorToId.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/meta/IsSourceReadOnly.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/meta/IsValidFunctionDescriptor.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/meta/NewAssociation.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/meta/NewClass.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/meta/NewEnumeration.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/meta/NewLambdaFunction.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/meta/NewProperty.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/meta/NewQualifiedProperty.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/runtime/CurrentUserId.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/runtime/IsOptionSet.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/ASCII.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/Char.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/Chunk.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/DecodeBase64.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/DecodeUrl.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/EncodeBase64.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/EncodeUrl.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/JaroWinklerSimilarity.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/LevenshteinDistance.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/Matches.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/RegexpCount.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/RegexpExtract.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/RegexpIndexOf.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/RegexpLike.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/string/RegexpReplace.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/functions/compiled/natives/tracing/TraceSpan.java",
    ],
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-functions-unclassified-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-runtime-java-extension-shared-functions-unclassified",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "@legend_maven//:commons_codec_commons_codec",
        "@legend_maven//:io_opentracing_opentracing_api",
        "@legend_maven//:io_opentracing_opentracing_util",
        "@legend_maven//:org_apache_commons_commons_text",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)

legend_java_library(
    name = "legend-engine-pure-runtime-java-extension-compiled-functions-unclassified",
    include_metadata = True,
    javacopts = ["-Xep:ComparableType:OFF"],
    pure_generator = ":Generator",
    pure_repository = "core_functions_unclassified",
    pure_srcs = ["//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-functions-unclassified-pure"],
    visibility = ["//visibility:public"],
    exports = [
        ":boot",
    ],
    deps = [
        ":boot",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-functions-unclassified-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-runtime-java-extension-shared-functions-unclassified",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "@legend_maven//:commons_codec_commons_codec",
        "@legend_maven//:io_opentracing_opentracing_api",
        "@legend_maven//:io_opentracing_opentracing_util",
        "@legend_maven//:org_apache_commons_commons_text",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
