load("@rules_java//java:defs.bzl", "java_library")
load("//legend-pure:grammar.bzl", "antlr_gen")

antlr_gen(
    name = "antlr_gen",
    srcs = glob(["src/main/antlr4/**/*.g4"]),
    tool = "//legend-pure:antlr4_tool",
    visibility = ["//visibility:private"],
)

java_library(
    name = "legend-engine-language-pure-grammar",
    srcs = [
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/ANTLRStringStream.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/CorePureGrammarParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/DEPRECATED_PureGrammarParserLibrary.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/DEPRECATED_SectionGrammarParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/ParseTreeWalkerSourceInformation.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/ParserErrorListener.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/PureGrammarParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/PureGrammarParserContext.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/PureGrammarParserUtility.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/PureIslandGrammarSourceCode.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/SectionSourceCode.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/SourceCodeParserInfo.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/connection/ConnectionParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/connection/ConnectionParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/connection/ModelConnectionParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/DataParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/embedded/ExternalFormatEmbeddedDataParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/embedded/HelperEmbeddedDataGrammarParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/embedded/ModelStoreDataParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/embedded/ModelStoreEmbeddedDataParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/embedded/ReferenceEmbeddedDataParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/embedded/RelationElementsEmbeddedDataParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/data/embedded/RelationElementsEmbeddedDataTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DateParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DomainParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/DomainParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/GraphFetchTreeParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/NavigationParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/ParserTreeWalkerUtility.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/domain/StrictTimeParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/extension/ConnectionValueParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/extension/EmbeddedPureParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/extension/MappingElementParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/extension/MappingTestInputDataParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/extension/PureGrammarParserExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/extension/PureGrammarParserExtensionLoader.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/extension/PureGrammarParserExtensions.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/extension/SectionParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/extension/data/EmbeddedDataParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/extension/test/assertion/TestAssertionParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/AggregationAwareMappingParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/EnumerationMappingParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/MappingElementSourceCode.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/MappingIncludeParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/MappingParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/MappingParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/OperationClassMappingParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/PureInstanceClassMappingParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/RelationFunctionMappingParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/mapping/XStoreAssociationMappingParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/relation/RelationStoreAccessorPureParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/runtime/PackageableElementPointerFactory.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/runtime/RuntimeParseTreeWalker.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/runtime/RuntimeParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/test/assertion/EqualToGrammarParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/test/assertion/EqualToJsonGrammarParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/from/test/assertion/HelperTestAssertionGrammarParser.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/CorePureGrammarComposer.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/DEPRECATED_PureGrammarComposerCore.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperConnectionGrammarComposer.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperDomainGrammarComposer.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperMappingGrammarComposer.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperRuntimeGrammarComposer.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/HelperValueSpecificationGrammarComposer.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/PureGrammarComposer.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/PureGrammarComposerContext.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/PureGrammarComposerUtility.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/data/HelperEmbeddedDataGrammarComposer.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/data/HelperRelationElementsDataComposer.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/data/ModelStoreDataGrammarComposer.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/extension/ContentWithType.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/extension/PureGrammarComposerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/extension/PureGrammarComposerExtensionLoader.java",
        "src/main/java/org/finos/legend/engine/language/pure/grammar/to/test/assertion/HelperTestAssertionGrammarComposer.java",
    ] + [":antlr_gen"],
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure:protocol-pure-v1",
        "//legend-engine/legend-engine-core/legend-engine-core-identity/legend-engine-identity-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-extensions",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:org_antlr_antlr4_runtime",
        "@legend_maven//:org_apache_commons_commons_lang3",
        "@legend_maven//:org_apache_commons_commons_text",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:org_slf4j_slf4j_api",
    ],
)
