load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "legend-engine-pure-functions-relation-pure",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        ":core_functions_relation_metadata_lib",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)

java_library(
    name = "core_functions_relation_metadata_lib",
    resources = [":core_functions_relation_metadata"],
    resource_strip_prefix = "legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure",
    visibility = ["//visibility:public"],
)

genrule(
    name = "core_functions_relation_metadata",
    srcs = ["src/main/resources/core_functions_relation.definition.json"],
    outs = ["metadata/specs/core_functions_relation.json"],
    cmd = "mkdir -p $$(dirname $@) && python3 -c \"import sys, json; d=json.load(sys.stdin); d.pop('pattern', None); print(json.dumps(d))\" < $< > $@",
    visibility = ["//visibility:public"],
)

java_binary(
    name = "compiled_metadata_generator",
    main_class = "org.finos.legend.pure.runtime.java.compiled.generation.orchestrator.JavaCodeGeneration",
    runtime_deps = [
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        ":legend-engine-pure-functions-relation-pure",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-functions-unclassified-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-variant/legend-engine-pure-functions-variant-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-runtime-java-extension-compiled-functions-relation",
    ],
    visibility = ["//visibility:public"],
)

genrule(
    name = "core_functions_relation_compiled_graph",
    srcs = glob(["src/main/resources/**/*"]),
    outs = ["core_functions_relation_compiled_metadata.jar"],
    tools = [":compiled_metadata_generator"],
    cmd = """
    mkdir -p $(@D)/relation_gen_out
    mkdir -p $(@D)/relation_classes_out
    export JAVA_OPTS="-Dpure.usePar=false"
    $(location :compiled_metadata_generator) \
        core_functions_relation \
        $(@D)/relation_classes_out \
        $(@D)/relation_gen_out

    jar cf $@ -C $(@D)/relation_classes_out metadata
    """,
    visibility = ["//visibility:public"],
)

java_import(
    name = "core_functions_relation_compiled_graph_import",
    jars = [":core_functions_relation_compiled_metadata.jar"],
    visibility = ["//visibility:public"],
)
