load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "legend-engine-language-pure-compiler",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "//legend-pure/legend-pure-core/legend-pure-m3-core:legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4:legend-pure-m4",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-pure:legend-pure-m2-dsl-mapping-pure",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-store/legend-pure-m2-dsl-store-pure:legend-pure-m2-dsl-store-pure",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-store/legend-pure-runtime-java-extension-compiled-dsl-store:legend-pure-runtime-java-extension-compiled-dsl-store",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-path/legend-pure-m2-dsl-path-pure:legend-pure-m2-dsl-path-pure",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-graph/legend-pure-m2-dsl-graph-pure:legend-pure-m2-dsl-graph-pure",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-path/legend-pure-runtime-java-extension-compiled-dsl-path:legend-pure-runtime-java-extension-compiled-dsl-path",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-graph/legend-pure-runtime-java-extension-compiled-dsl-graph:legend-pure-runtime-java-extension-compiled-dsl-graph",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-runtime-java-extension-compiled-dsl-mapping:legend-pure-runtime-java-extension-compiled-dsl-mapping",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled:legend-pure-runtime-java-engine-compiled",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core:legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol:legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure:protocol-pure-v1",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core:legend-engine-shared-core",
        "//legend-engine/legend-engine-core/legend-engine-core-identity/legend-engine-identity-core:legend-engine-identity-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-extensions:legend-engine-shared-extensions",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_slf4j_slf4j_api",
        "@legend_maven//:org_apache_commons_commons_lang3",
    ],
    javacopts = [
        "-Xep:IdentityBinaryExpression:OFF",
        "-Xep:SelfAssertion:OFF",
    ],
)
