load("@rules_java//java:defs.bzl", "java_library", "java_test")

java_library(
    name = "legend-engine-language-pure-compiler",
    srcs = [
        "src/main/java/org/finos/legend/engine/language/pure/compiler/Compiler.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/MetadataWrapper.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/fromPureGraph/PureModelContextDataGenerator.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/AssociationCompilerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/AutoCloseableLock.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ClassCompilerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ClassMappingFirstPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ClassMappingPrerequisiteElementsPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ClassMappingSecondPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ClassMappingThirdPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/CompileContext.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ConnectionFirstPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ConnectionSecondPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/CoreCompilerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DataElementCompilerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/DependencyManagement.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/EnumerationCompilerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/FunctionCompilerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/GraphValueSpecificationToProtocol.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperConnectionBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperFunctionBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperMappingBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperMeasureBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperModelBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperRuntimeBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/HelperValueSpecificationBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/IPureModel.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/MappingCompilerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/MeasureCompilerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/Milestoning.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/MilestoningDatePropagationContext.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/MilestoningDatePropagationHelper.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableConnectionCompilerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableElementMilestoningPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PackageableRuntimeCompilerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PrimitiveProcessor.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ProcessingContext.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ProfileCompilerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PropertyMappingBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PropertyMappingPrerequisiteElementsBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModel.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/PureModelProcessParameter.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/RelationTypeHelper.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/SectionIndexCompilerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/SourceInformationHelper.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/TestCompilerHelper.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ValueSpecificationBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/ValueSpecificationPrerequisiteElementsPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/Warning.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/data/EmbeddedDataFirstPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/data/EmbeddedDataPrerequisiteElementsPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/data/core/EmbeddedDataCompilerHelper.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/defect/Defect.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/defect/DefectSeverityLevel.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/CompilerExtension.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/CompilerExtensionLoader.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/CompilerExtensions.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/Processor.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/FuncHandlerLazyState.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/FunctionExpressionBuilderRegistrationInfo.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/FunctionHandler.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/FunctionHandlerDispatchBuilderInfo.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/FunctionHandlerRegistrationInfo.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/Handlers.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/IncludedMappingHandler.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/MappingIncludedMappingHandler.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/RuntimeCompilerHandler.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/StoreProviderCompilerHelper.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/UserDefinedFunctionHandler.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/builder/CompositeFunctionExpressionBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/builder/FunctionExpressionBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/builder/MultiHandlerFunctionExpressionBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/builder/RequiredInferenceSimilarSignatureFunctionExpressionBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/inference/Dispatch.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/inference/MostCommonMultiplicity.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/inference/MostCommonType.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/inference/ParametersInference.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/inference/ResolveTypeParameterInference.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/inference/ReturnInference.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/handlers/inference/TypeAndMultiplicity.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/test/ModelStoreTestConnectionFactory.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/test/RelationAccessorTestConnectionFactory.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/test/TestBuilderHelper.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/test/TestFirstPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/test/TestPrerequisiteElementsPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/test/assertion/TestAssertionFirstPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/test/assertion/TestAssertionPrerequisiteElementsPassBuilder.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/test/assertion/core/TestAssertionCompilerHelper.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/AssociationValidator.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/ClassValidator.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/EnumerationValidator.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/FunctionValidator.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/MappingValidator.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/MappingValidatorContext.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/ProfileValidator.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/PureModelContextDataValidator.java",
        "src/main/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/validator/StoreValidator.java",
    ],
    javacopts = [
        "-Xep:IdentityBinaryExpression:OFF",
        "-Xep:SelfAssertion:OFF",
    ],
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure:protocol-pure-v1",
        "//legend-engine/legend-engine-core/legend-engine-core-identity/legend-engine-identity-core",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-platform-modular-generation/legend-engine-pure-platform-dsl-mapping-java",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-platform-modular-generation/legend-engine-pure-platform-dsl-store-java",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-platform-modular-generation/legend-engine-pure-platform-java",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-platform-modular-generation/legend-engine-pure-platform-precisePrimitives-java",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-extensions",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-graph/legend-pure-m2-dsl-graph-pure",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-graph/legend-pure-runtime-java-extension-compiled-dsl-graph",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-pure",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-runtime-java-extension-compiled-dsl-mapping",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-path/legend-pure-m2-dsl-path-pure",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-path/legend-pure-runtime-java-extension-compiled-dsl-path",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-store/legend-pure-m2-dsl-store-pure",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-store/legend-pure-runtime-java-extension-compiled-dsl-store",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:org_apache_commons_commons_lang3",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:org_slf4j_slf4j_api",
    ],
)
java_library(
    name = "test_utils",
    srcs = [
        "src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/EmbeddedPureCompilerExtension.java",
        "src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestCompilationFromGrammar.java",
        "src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestCompilationFromProtocol.java",
    ],
    deps = [
        ":legend-engine-language-pure-compiler",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar:grammar-test-utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure:protocol-pure-v1",
        "//legend-engine/legend-engine-core/legend-engine-core-identity/legend-engine-identity-core",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-platform-modular-generation/legend-engine-pure-platform-java",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled:core_gen",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled:compiled_engine_boot",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_hamcrest_hamcrest_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
    ],
    visibility = ["//visibility:public"],
)

java_test(
    name = "CompilerTest",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/CompilerTest.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.CompilerTest",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure:protocol-pure-v1",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TemporaryGrammarTest_WIP",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/TemporaryGrammarTest_WIP.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.TemporaryGrammarTest_WIP",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestAggregationAwareCompilationFromGrammar",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestAggregationAwareCompilationFromGrammar.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.fromGrammar.TestAggregationAwareCompilationFromGrammar",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)




java_test(
    name = "TestCompilerExtensions",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/extension/TestCompilerExtensions.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.toPureGraph.extension.TestCompilerExtensions",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestConnectionCompilationFromGrammar",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestConnectionCompilationFromGrammar.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.fromGrammar.TestConnectionCompilationFromGrammar",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestDataCompilationFromGrammar",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDataCompilationFromGrammar.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.fromGrammar.TestDataCompilationFromGrammar",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestDependencyManagement",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/toPureGraph/TestDependencyManagement.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.toPureGraph.TestDependencyManagement",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestDomainCompilationFromGrammar",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestDomainCompilationFromGrammar.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.fromGrammar.TestDomainCompilationFromGrammar",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestDomainCompilationFromProtocol",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromProtocol/TestDomainCompilationFromProtocol.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.fromProtocol.TestDomainCompilationFromProtocol",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestFunctionCompilationFromGrammar",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestFunctionCompilationFromGrammar.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.fromGrammar.TestFunctionCompilationFromGrammar",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestHandlersValidation",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestHandlersValidation.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.TestHandlersValidation",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestHelperModelBuilder",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestHelperModelBuilder.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.TestHelperModelBuilder",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure:protocol-pure-v1",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestMappingCompilationFromGrammar",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMappingCompilationFromGrammar.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.fromGrammar.TestMappingCompilationFromGrammar",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestMappingCompilationFromProtocol",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromProtocol/TestMappingCompilationFromProtocol.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.fromProtocol.TestMappingCompilationFromProtocol",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestMilestonedPropertyUsageInFunctionExpresions",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMilestonedPropertyUsageInFunctionExpresions.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.fromGrammar.TestMilestonedPropertyUsageInFunctionExpresions",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestMilestonedPropertyUsageInGraphFetch",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestMilestonedPropertyUsageInGraphFetch.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.fromGrammar.TestMilestonedPropertyUsageInGraphFetch",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestRelationNotUsingDatabaseAccessor",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestRelationNotUsingDatabaseAccessor.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.fromGrammar.TestRelationNotUsingDatabaseAccessor",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestRoundTripWithPureTransformation",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestRoundTripWithPureTransformation.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.TestRoundTripWithPureTransformation",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestRuntimeCompilationFromGrammar",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestRuntimeCompilationFromGrammar.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.fromGrammar.TestRuntimeCompilationFromGrammar",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestSectionCompilationFromGrammar",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/fromGrammar/TestSectionCompilationFromGrammar.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.fromGrammar.TestSectionCompilationFromGrammar",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

java_test(
    name = "TestToPureGrammarRoundtrip",
    srcs = ["src/test/java/org/finos/legend/engine/language/pure/compiler/test/TestToPureGrammarRoundtrip.java"],
    test_class = "org.finos.legend.engine.language.pure.compiler.test.TestToPureGrammarRoundtrip",
    deps = [
        ":legend-engine-language-pure-compiler",
        ":test_utils",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-language-pure-grammar",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-core",
        "@legend_maven//:junit_junit",
        "@legend_maven//:org_assertj_assertj_core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:commons_io_commons_io",
    ],
)

