load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "legend-engine-shared-core",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure:protocol-pure-v1",
        "//legend-engine/legend-engine-core/legend-engine-core-identity/legend-engine-identity-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-extensions",
        "//legend-engine/legend-engine-xts-identity/legend-engine-xt-identity-pac4j",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:io_opentracing_opentracing_api",
        "@legend_maven//:io_opentracing_opentracing_util",
        "@legend_maven//:io_prometheus_simpleclient",
        "@legend_maven//:io_zipkin_reporter2_zipkin_reporter",
        "@legend_maven//:javax_ws_rs_javax_ws_rs_api",
        "@legend_maven//:org_apache_commons_commons_lang3",
        "@legend_maven//:org_apache_httpcomponents_httpclient",
        "@legend_maven//:org_apache_httpcomponents_httpcore",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:org_pac4j_pac4j_core",
        "@legend_maven//:org_slf4j_slf4j_api",
    ],
)
