load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "legend-engine-shared-core",
    srcs = [
        "src/main/java/org/finos/legend/engine/shared/core/api/grammar/BatchResult.java",
        "src/main/java/org/finos/legend/engine/shared/core/api/grammar/GrammarAPI.java",
        "src/main/java/org/finos/legend/engine/shared/core/api/grammar/ParserError.java",
        "src/main/java/org/finos/legend/engine/shared/core/api/grammar/Parser.java",
        "src/main/java/org/finos/legend/engine/shared/core/api/grammar/RenderStyle.java",
        "src/main/java/org/finos/legend/engine/shared/core/api/model/ExecuteInput.java",
        "src/main/java/org/finos/legend/engine/shared/core/api/request/RequestContext.java",
        "src/main/java/org/finos/legend/engine/shared/core/api/result/ConstantResultHelper.java",
        "src/main/java/org/finos/legend/engine/shared/core/api/result/ManageConstantResult.java",
        "src/main/java/org/finos/legend/engine/shared/core/collectionsExtensions/DoubleHashingStrategy.java",
        "src/main/java/org/finos/legend/engine/shared/core/collectionsExtensions/DoubleStrategyHashMap.java",
        "src/main/java/org/finos/legend/engine/shared/core/deployment/DeploymentMode.java",
        "src/main/java/org/finos/legend/engine/shared/core/deployment/DeploymentStateAndVersions.java",
        "src/main/java/org/finos/legend/engine/shared/core/deployment/DeploymentVersionInfo.java",
        "src/main/java/org/finos/legend/engine/shared/core/function/Function4.java",
        "src/main/java/org/finos/legend/engine/shared/core/function/Function5.java",
        "src/main/java/org/finos/legend/engine/shared/core/function/Procedure3.java",
        "src/main/java/org/finos/legend/engine/shared/core/function/Procedure4.java",
        "src/main/java/org/finos/legend/engine/shared/core/kerberos/HttpClientBuilder.java",
        "src/main/java/org/finos/legend/engine/shared/core/LightScheduler.java",
        "src/main/java/org/finos/legend/engine/shared/core/ObjectMapperFactory.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/Assert.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/EngineException.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/ExceptionCategoryData.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/ExceptionCategory.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/ExceptionError.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/errorManagement/ExceptionTool.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/http/InflateInterceptor.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/logs/ILoggingEventType.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/logs/LoggingEventType.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/logs/LogInfo.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/opentracing/HttpRequestHeaderMap.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/prometheus/MetricsHandler.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/prometheus/Prometheus.java",
        "src/main/java/org/finos/legend/engine/shared/core/operational/prometheus/TracingExports.java",
        "src/main/java/org/finos/legend/engine/shared/core/port/DynamicPortGenerator.java",
        "src/main/java/org/finos/legend/engine/shared/core/url/DataProtocolHandler.java",
        "src/main/java/org/finos/legend/engine/shared/core/url/EngineUrlStreamHandlerFactory.java",
        "src/main/java/org/finos/legend/engine/shared/core/url/ExecutorProtocolHandler.java",
        "src/main/java/org/finos/legend/engine/shared/core/url/InputStreamProvider.java",
        "src/main/java/org/finos/legend/engine/shared/core/url/NamedInputStream.java",
        "src/main/java/org/finos/legend/engine/shared/core/url/NamedInputStreamProvider.java",
        "src/main/java/org/finos/legend/engine/shared/core/url/StreamProviderHolder.java",
        "src/main/java/org/finos/legend/engine/shared/core/url/StreamProvider.java",
        "src/main/java/org/finos/legend/engine/shared/core/url/UrlFactory.java",
        "src/main/java/org/finos/legend/engine/shared/core/url/UrlProtocolHandler.java",
        "src/main/java/org/finos/legend/engine/shared/core/util/LimitedByteArrayOutputStream.java",
        "src/main/java/org/finos/legend/engine/shared/core/util/ResourceHelpers.java",
    ],
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol-pure:protocol-pure-v1",
        "//legend-engine/legend-engine-core/legend-engine-core-identity/legend-engine-identity-core",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-extensions",
        "//legend-engine/legend-engine-xts-identity/legend-engine-xt-identity-pac4j",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:io_opentracing_opentracing_api",
        "@legend_maven//:io_opentracing_opentracing_util",
        "@legend_maven//:io_prometheus_simpleclient",
        "@legend_maven//:io_zipkin_reporter2_zipkin_reporter",
        "@legend_maven//:javax_ws_rs_javax_ws_rs_api",
        "@legend_maven//:org_apache_commons_commons_lang3",
        "@legend_maven//:org_apache_httpcomponents_httpclient",
        "@legend_maven//:org_apache_httpcomponents_httpcore",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:org_pac4j_pac4j_core",
        "@legend_maven//:org_slf4j_slf4j_api",
    ],
)
