load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "legend-engine-pure-runtime-java-extension-shared-functions-json",
    srcs = [
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/DefaultJsonExtraTypeProcessor.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonAnyTypeDeserialization.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonClassDeserialization.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonClassSerialization.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonContext.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonDeserializationCache.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonDeserializationContext.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonDeserializationMultiplicityMany.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonDeserializationMultiplicityOne.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonDeserializationMultiplicityOptional.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonDeserializationMultiplicityParameterised.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonDeserializationMultiplicityRange.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonDeserializer.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonEnumerationDeserialization.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonEnumerationSerialization.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonExtraTypeProcessor.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonGenericAndAnyTypeSerialization.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonMapDeserialization.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonMapSerialization.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonParser.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonPropertyDeserialization.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonPropertySerialization.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonQualifiedPropertySerialization.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonSerializationCache.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonSerializationContext.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonSerializationMultiplicityMany.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonSerializationMultiplicityOne.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonSerializationMultiplicityOptional.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonSerializationMultiplicityParameterised.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonSerializationMultiplicityRange.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonSerializer.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonUnitDeserialization.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/JsonUnitSerialization.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/shared/MetamodelSerializationOverrides.java",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-runtime-java-extension-shared-functions-conversion",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-runtime-java-extension-shared-functions-unclassified",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "@legend_maven//:com_googlecode_json_simple_json_simple",
        "@legend_maven//:commons_codec_commons_codec",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
