load("@rules_java//java:defs.bzl", "java_binary", "java_library")
load("//tools/build_rules:legend_java_library.bzl", "legend_java_library")

java_library(
    name = "resources",
    javacopts = ["-Xep:ComparableType:OFF"],
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
)

java_binary(
    name = "Generator",
    javacopts = ["-Xep:ComparableType:OFF"],
    main_class = "org.finos.legend.pure.runtime.java.compiled.generation.orchestrator.JavaCodeGeneration",
    visibility = ["//visibility:public"],
    runtime_deps = [
        ":boot",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-functions-json-pure",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "@legend_maven//:com_googlecode_json_simple_json_simple",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)

java_library(
    name = "boot",
    srcs = [
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/compiled/CompiledJsonExtraTypeProcessor.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/compiled/JsonExtensionCompiled.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/compiled/JsonNativeImplementation.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/compiled/PureMapSerializer.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/compiled/natives/EqualJsonStrings.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/compiled/natives/Escape.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/compiled/natives/FromJson.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/compiled/natives/FromJsonDeprecated.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/compiled/natives/JsonParserHelper.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/compiled/natives/ParseJSON.java",
        "src/main/java/org/finos/legend/pure/runtime/java/extension/external/json/compiled/natives/ToJsonBeta.java",
    ],
    javacopts = ["-Xep:ComparableType:OFF"],
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-functions-json-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-runtime-java-extension-shared-functions-conversion",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-runtime-java-extension-shared-functions-json",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-runtime-java-extension-compiled-functions-unclassified",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "@legend_maven//:com_googlecode_json_simple_json_simple",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)

legend_java_library(
    name = "legend-engine-pure-runtime-java-extension-compiled-functions-json",
    srcs = [],
    include_metadata = True,
    javacopts = ["-Xep:ComparableType:OFF"],
    pure_generator = ":Generator",
    pure_repository = "core_functions_json",
    pure_srcs = ["//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-functions-json-pure"],
    src_root = "legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-runtime-java-extension-compiled-functions-json/src/main/java",
    visibility = ["//visibility:public"],
    exports = [
        ":boot",
    ],
    deps = [
        ":boot",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-functions-json-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-runtime-java-extension-shared-functions-conversion",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-runtime-java-extension-shared-functions-json",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-runtime-java-extension-compiled-functions-unclassified",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "@legend_maven//:com_googlecode_json_simple_json_simple",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
