load("@rules_java//java:defs.bzl", "java_binary", "java_library")

java_library(
    name = "resources",
    resources = glob(["src/main/resources/**/*"]),
    javacopts = ["-Xep:ComparableType:OFF"],
    visibility = ["//visibility:public"],
)

java_binary(
    name = "Generator",
    main_class = "org.finos.legend.pure.runtime.java.compiled.generation.orchestrator.JavaCodeGeneration",
    runtime_deps = [
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled:legend-pure-runtime-java-engine-compiled",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-functions-json-pure",
        "//legend-pure/legend-pure-core/legend-pure-m3-core:legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4:legend-pure-m4",
        "@maven//:com_googlecode_json_simple_json_simple",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        ":boot",
    ],
    javacopts = ["-Xep:ComparableType:OFF"],
    visibility = ["//visibility:public"],
)

genrule(
    name = "generate_sources",
    outs = ["core_functions_json_src.srcjar"],
    cmd = """
        mkdir -p work_dir/classes
        mkdir -p work_dir/target

        $(location :Generator) \
            core_functions_json \
            work_dir/classes \
            work_dir/target

        if [ -d work_dir/target/generated-sources ]; then
             cd work_dir/target/generated-sources
             zip -q -r ../../../$(location core_functions_json_src.srcjar) .
             cd ../../..
        elif [ -d work_dir/target/generated-test-sources ]; then
             cd work_dir/target/generated-test-sources
             zip -q -r ../../../$(location core_functions_json_src.srcjar) .
             cd ../../..
        else
             echo "No sources generated"
             ls -R work_dir
             exit 1
        fi
    """,
    tools = [":Generator"],
    visibility = ["//visibility:public"],
)


java_library(
    name = "boot",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**/*"]),
    deps = [
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled:legend-pure-runtime-java-engine-compiled",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-functions-json-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-runtime-java-extension-shared-functions-json",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-runtime-java-extension-shared-functions-conversion",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-runtime-java-extension-compiled-functions-unclassified",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:com_googlecode_json_simple_json_simple",
        "//legend-pure/legend-pure-core/legend-pure-m3-core:legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4:legend-pure-m4",
    ],
    javacopts = ["-Xep:ComparableType:OFF"],
    visibility = ["//visibility:public"],
)

java_library(
    name = "legend-engine-pure-runtime-java-extension-compiled-functions-json",
    srcs = [":core_functions_json_src.srcjar"],
    deps = [
        ":boot",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled:legend-pure-runtime-java-engine-compiled",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-functions-json-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-runtime-java-extension-shared-functions-json",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-runtime-java-extension-shared-functions-conversion",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-runtime-java-extension-compiled-functions-unclassified",
        "@maven//:org_eclipse_collections_eclipse_collections",
        "@maven//:org_eclipse_collections_eclipse_collections_api",
        "@maven//:com_googlecode_json_simple_json_simple",
        "//legend-pure/legend-pure-core/legend-pure-m3-core:legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m4:legend-pure-m4",
    ],
    exports = [
        ":boot",
    ],
    javacopts = ["-Xep:ComparableType:OFF"],
    visibility = ["//visibility:public"],
)
