load("@rules_java//java:defs.bzl", "java_binary", "java_library")
load("//tools/build_rules:pure_generation.bzl", "pure_protocol_generation")

java_binary(
    name = "Generator",
    main_class = "org.finos.legend.engine.protocol.generation.GenerateMetaClasses",
    jvm_flags = ["-Xmx4G"],
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    runtime_deps = [
        "//legend-engine/legend-engine-xts-protocol-java-generation/legend-engine-protocol-generation",
        "//legend-pure/legend-pure-core/legend-pure-m3-core",
        "//legend-pure/legend-pure-core/legend-pure-m3-core:platform_compiled_graph_import",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-pure",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-runtime-java-extension-compiled-dsl-mapping",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-graph/legend-pure-m2-dsl-graph-pure:platform_dsl_graph_compiled_graph_import",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-store/legend-pure-m2-dsl-store-pure:platform_dsl_store_compiled_graph_import",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-mapping/legend-pure-m2-dsl-mapping-pure:platform_dsl_mapping_compiled_graph_import",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-tds/legend-pure-m2-dsl-tds-pure:platform_dsl_tds_compiled_graph_import",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-path/legend-pure-m2-dsl-path-pure:platform_dsl_path_compiled_graph_import",
        "//legend-pure/legend-pure-dsl/legend-pure-dsl-diagram/legend-pure-m2-dsl-diagram-pure:platform_dsl_diagram_compiled_graph_import",
        "//legend-pure/legend-pure-store/legend-pure-store-relational/legend-pure-m2-store-relational-pure:platform_store_relational_compiled_graph_import",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-unclassified/legend-engine-pure-functions-unclassified-pure:core_functions_unclassified_compiled_graph_import",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-standard/legend-engine-pure-functions-standard-pure:core_functions_standard_compiled_graph_import",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-relation/legend-engine-pure-functions-relation-pure:core_functions_relation_compiled_graph_import",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-json/legend-engine-pure-functions-json-pure:core_functions_json_compiled_graph_import",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-variant/legend-engine-pure-functions-variant-pure:core_functions_variant_compiled_graph_import",
        "//legend-engine/legend-engine-xts-java/legend-engine-xt-javaGeneration-pure:core_external_language_java_compiled_graph_import",
        "//legend-engine/legend-engine-xts-java/legend-engine-xt-javaGeneration-conventions-essential-pure:core_external_language_java_conventions_essential_compiled_graph_import",
        "//legend-engine/legend-engine-xts-java/legend-engine-xt-javaGeneration-conventions-standard-pure:core_external_language_java_conventions_standard_compiled_graph_import",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-functions-javaCompiler/legend-engine-pure-functions-javaCompiler-pure:core_external_language_java_compiler_compiled_graph_import",
        "//legend-engine/legend-engine-core/legend-engine-core-pure/legend-engine-pure-code-compiled-core",
    ],
)

pure_protocol_generation(
    name = "protocol_pure_src",
    src = "src/main/resources/m3.protocol.json",
    tool = ":Generator",
    visibility = ["//visibility:public"],
)

java_library(
    name = "legend-engine-protocol-pure",
    srcs = [":protocol_pure_src.srcjar"],
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-extensions",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:org_mongodb_bson",
        "@legend_maven//:org_slf4j_slf4j_api",
    ],
)


load("//tools/build_rules:java_validation.bzl", "validated_java_library")

java_library(
    name = "protocol-pure-v1",
    srcs = [
        "src/main/java/org/finos/legend/engine/protocol/pure/dsl/graph/valuespecification/constant/classInstance/GraphFetchTree.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/dsl/graph/valuespecification/constant/classInstance/GraphFetchTreeVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/dsl/graph/valuespecification/constant/classInstance/PropertyGraphFetchTree.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/dsl/graph/valuespecification/constant/classInstance/RootGraphFetchTree.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/dsl/graph/valuespecification/constant/classInstance/SubTypeGraphFetchTree.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/dsl/path/valuespecification/constant/classInstance/PathElement.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/dsl/path/valuespecification/constant/classInstance/Path.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/dsl/path/valuespecification/constant/classInstance/PropertyPathElement.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/dsl/store/valuespecification/constant/classInstance/RelationStoreAccessor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/constraint/Constraint.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/extension/Profile.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/extension/ProfileStereotype.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/extension/ProfileTag.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/extension/StereotypePtr.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/extension/TaggedValue.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/extension/TagPtr.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/function/Function.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/function/LambdaFunction.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/function/property/AggregationKind.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/function/property/DefaultValue.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/function/property/Property.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/function/property/QualifiedProperty.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/multiplicity/Multiplicity.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/PackageableElement.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/relation/Column.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/relation/RelationType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/relationship/Association.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/type/Class.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/type/Enumeration.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/type/EnumValue.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/type/generics/GenericType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/type/Measure.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/type/Type.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/type/Unit.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/AbstractAppliedFunction.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/AppliedFunction.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/AppliedProperty.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/Collection.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/classInstance/ClassInstance.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/classInstance/relation/ColSpecArray.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/classInstance/relation/ColSpec.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/DataTypeValueSpecification.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/EnumValue.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/primitive/CBoolean.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/primitive/CByteArray.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/primitive/CDate.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/primitive/CDateTime.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/primitive/CDecimal.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/primitive/CFloat.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/primitive/CInteger.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/primitive/CLatestDate.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/primitive/CStrictDate.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/primitive/CStrictTime.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/primitive/CString.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/primitive/PrimitiveValueSpecification.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/datatype/UnitInstance.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/GenericTypeInstance.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/PackageableElementPtr.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/constant/PackageableType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/Many.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/One.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/ValueSpecification.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/ValueSpecificationVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/m3/valuespecification/Variable.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/PureClientVersions.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/CorePureProtocolExtension.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/extension/ConnectionFactoryExtension.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/extension/ProtocolConverter.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/extension/ProtocolSubTypeInfo.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/extension/PureProtocolExtension.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/extension/PureProtocolExtensionLoader.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/extension/TestAssertionEvaluator.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/AlloySDLC.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/EngineErrorType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/LegacySDLC.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/PackageableElementPointer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/PackageableElementType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/PureModelContextCombination.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/PureModelContextConcrete.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/PureModelContextData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/PureModelContext.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/PureModelContextPointer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/PureModelContextText.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/PureSDLC.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/SDLC.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/SDLCVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/context/WorkspaceSDLC.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/DataElementReference.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/EmbeddedDataHelper.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/EmbeddedData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/EmbeddedDataVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/ExternalFormatData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/ModelEmbeddedTestData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/ModelInstanceTestData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/ModelStoreData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/ModelTestData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/relation/RelationElement.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/relation/RelationElementsData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/data/relation/RelationRowTestData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/domain/Domain.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionOption/ExecutionOption.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/CompositeExecutionPlan.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/ExecutionPlan.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/AggregationAwareExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/AllocationExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/CompiledClass.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ConstantExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/EnumValidationContext.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ErrorExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ExecutionNodeVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/externalFormat/DataQualityExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/externalFormat/ExternalFormatDeserializeExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/externalFormat/ExternalFormatExternalizeExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/externalFormat/ExternalFormatExternalizeTDSExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/externalFormat/ExternalFormatInternalizeExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/externalFormat/ExternalFormatSerializeExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/externalFormat/PathReference.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/externalFormat/UrlStreamExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/externalFormat/VariableResolutionExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/FreeMarkerConditionalExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/FunctionParametersValidationNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/GlobalGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/GraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/LocalGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/GraphFetchM2MExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/PlatformGlobalGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/PlatformPrimitiveQualifierLocalGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/store/inMemory/InMemoryCrossStoreGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/store/inMemory/InMemoryGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/store/inMemory/InMemoryPropertyGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/store/inMemory/InMemoryRootGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/store/inMemory/StoreStreamReadingExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/StoreMappingGlobalGraphFetchExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/graphFetch/XStorePropertyFetchDetails.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/JavaClass.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/JavaPlatformImplementation.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/MultiResultSequenceExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ParameterValidationContext.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ParameterValidationContextVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/PlatformImplementation.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/PlatformMergeExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/PlatformUnionExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/ProtocolObjectValidationContext.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/PureExpressionPlatformExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/SequenceExecutionNode.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/nodes/VariableInput.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/result/ClassResultType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/result/DataTypeResultType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/result/PartialClassResultType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/result/PropertyMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/result/PropertyWithParameters.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/result/ResultType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/result/SetImplementationPtr.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/result/TDSColumn.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/result/TDSResultType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/result/VoidResultType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/executionPlan/SingleExecutionPlan.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/connection/Connection.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/connection/ConnectionPointer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/connection/ConnectionVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/connection/PackageableConnection.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/data/DataElement.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/domain/ModelUnit.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/domain/ParameterValue.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/externalFormat/Binding.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/externalFormat/BindingTransformer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/externalFormat/ExternalFormatSchema.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/externalFormat/ExternalFormatSchemaSet.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/function/ConnectionTestData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/function/FunctionTestData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/function/FunctionTest.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/function/FunctionTestSuite.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapper/DatabaseMapper.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapper/RelationalMapper.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapper/SchemaMapper.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapper/SchemaPtr.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapper/TableMapper.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapper/TablePtr.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/aggregationAware/AggregateFunction.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/aggregationAware/AggregateSetImplementationContainer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/aggregationAware/AggregateSpecification.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/aggregationAware/AggregationAwareClassMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/aggregationAware/AggregationAwarePropertyMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/aggregationAware/GroupByFunction.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/AssociationMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/ClassMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/ClassMappingVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/EnumerationMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/EnumValueMappingEnumSourceValue.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/EnumValueMappingIntegerSourceValue.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/EnumValueMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/EnumValueMappingSourceValueDeserializer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/EnumValueMappingSourceValue.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/EnumValueMappingSourceValueSerializer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/EnumValueMappingStringSourceValue.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/LocalMappingPropertyInfo.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/MappingClass.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/MappingInclude.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/MappingIncludeMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/Mapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/MappingOperation.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/ExpectedOutputMappingTestAssert.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/InputData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingTestAssert.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingTest.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingTest_Legacy.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/MappingTestSuite.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/mappingTest/StoreTestData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/MergeOperationClassMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/OperationClassMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/PropertyMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/PropertyMappingVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/PropertyPointer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/relationFunction/RelationFunctionClassMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/relationFunction/RelationFunctionPropertyMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/xStore/XStoreAssociationMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/mapping/xStore/XStorePropertyMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/multiplicity/MultiplicityPointer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/PackageableElementVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/runtime/ConnectionStore.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/runtime/ConnectionStores.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/runtime/EngineRuntime.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/runtime/IdentifiedConnection.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/runtime/LegacyRuntime.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/runtime/PackageableRuntime.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/runtime/Runtime.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/runtime/RuntimePointer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/runtime/SingleConnectionEngineRuntime.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/runtime/StoreConnections.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/section/DefaultCodeSection.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/section/ImportAwareCodeSection.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/section/SectionIndex.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/section/Section.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/IncludeStore.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/connection/JsonModelConnection.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/connection/ModelChainConnection.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/connection/ModelConnection.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/connection/ModelInput.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/connection/ModelStringInput.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/connection/PureModelConnection.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/connection/XmlModelConnection.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/mapping/ObjectInputData.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/mapping/ObjectInputType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/mapping/PureInstanceClassMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/mapping/PurePropertyMapping.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/modelToModel/ModelStore.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/Store.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/packageableElement/store/StoreProviderPointer.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/assertion/EqualTo.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/assertion/EqualToJson.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/assertion/status/AssertFail.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/assertion/status/AssertionStatus.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/assertion/status/AssertPass.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/assertion/status/EqualToJsonAssertFail.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/assertion/TestAssertion.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/assertion/TestAssertionVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/AtomicTest.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/result/TestDebug.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/result/TestError.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/result/TestExecuted.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/result/TestExecutionPlanDebug.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/result/TestExecutionStatus.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/result/TestResult.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/Test.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/TestSuite.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/test/TestVisitor.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/ClassInstanceWrapper.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/deprecated/AppliedQualifiedProperty.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/deprecated/Class.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/deprecated/Enum.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/deprecated/HackedClass.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/deprecated/HackedUnit.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/deprecated/MappingInstance.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/deprecated/PrimitiveType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/deprecated/UnknownAppliedFunction.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/deprecated/Whatever.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/classInstance/AggregateValue.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/classInstance/ExecutionContextInstance.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/classInstance/Pair.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/classInstance/PureList.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/classInstance/RuntimeInstance.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/classInstance/SerializationConfig.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/classInstance/TDSAggregateValue.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/classInstance/TDSColumnInformation.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/classInstance/TdsOlapAggregation.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/classInstance/TdsOlapRank.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/classInstance/TDSSortInformation.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/CoreClassInstances.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/executionContext/AnalyticsExecutionContext.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/executionContext/BaseExecutionContext.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/executionContext/ExecutionContext.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/KeyExpression.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/model/valueSpecification/raw/UnitType.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/ProcessHelper.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/ProtocolToClassifierPathLoader.java",
        "src/main/java/org/finos/legend/engine/protocol/pure/v1/PureProtocolObjectMapperFactory.java",
    ],
    resources = glob(["src/main/resources/**/*"]),
    visibility = ["//visibility:public"],
    deps = [
        ":legend-engine-protocol-pure",
        "//legend-engine/legend-engine-core/legend-engine-core-base/legend-engine-core-language-pure/legend-engine-protocol",
        "//legend-engine/legend-engine-core/legend-engine-core-shared/legend-engine-shared-extensions",
        "//legend-pure/legend-pure-runtime/legend-pure-runtime-java-engine-compiled",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_core",
        "@legend_maven//:com_fasterxml_jackson_core_jackson_databind",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
        "@legend_maven//:org_mongodb_bson",
        "@legend_maven//:org_slf4j_slf4j_api",
    ],
)
