load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "legend-engine-xt-identity-kerberos",
    srcs = [
        "src/main/java/org/finos/legend/engine/identity/extension/kerberos/KerberosSubjectIdentityFactory.java",
        "src/main/java/org/finos/legend/engine/shared/core/identity/credential/KerberosUtils.java",
        "src/main/java/org/finos/legend/engine/shared/core/identity/credential/LegendKerberosCredential.java",
        "src/main/java/org/finos/legend/engine/shared/core/kerberos/ExecSubject.java",
        "src/main/java/org/finos/legend/engine/shared/core/kerberos/LocalLoginConfiguration.java",
        "src/main/java/org/finos/legend/engine/shared/core/kerberos/SubjectCache.java",
        "src/main/java/org/finos/legend/engine/shared/core/kerberos/SubjectTools.java",
        "src/main/java/org/finos/legend/engine/shared/core/kerberos/SystemAccountLoginConfiguration.java",
        "src/main/java/org/finos/legend/engine/shared/core/kerberos/UsernamePasswordAccountLoginConfiguration.java",
    ],
    javacopts = ["-Xep:SelfAssignment:OFF"],
    visibility = ["//visibility:public"],
    deps = [
        "//legend-engine/legend-engine-core/legend-engine-core-identity/legend-engine-identity-core",
        "@legend_maven//:org_eclipse_collections_eclipse_collections",
        "@legend_maven//:org_eclipse_collections_eclipse_collections_api",
    ],
)
